name: nlp_final
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - pandas=2.1.4
  - matplotlib
  - gensim=4.3.2
  - nltk
  - pip
  - pip:
      - streamlit
